### ISSUE TITLE
Executing test app command is not working in windows

### ISSUE THREAD

**Issue by thakursachin05** [neutralinojs/neutralinojs.github.io#189]
Executing the test app command in windows : - **bash ./scripts/update_client.sh** 
is not creating the **neutralino-win_x64.exe** file in bin folder. It only creates resources directory,

**Comment by shalithasuranga** [comment]
Hello @thakursachin05 .. Thanks for reporting this issue. `update_client.sh` is responsible for updating the `neutralino.js` file (client library) in the test project. On Windows, it will work with Git bash terminal since it supports Unix commands.

To create the framework binary (`.exe`) on Windows, please run the `./scripts/bz.py` script.
